#!/usr/bin/env bash

handle() {
    case $1 in
    activespecialv2*)
        local event_data="${1#*>>}"
        if [[ "$event_data" == ",,"* ]]; then
            echo "false"
        else
            echo "true"
        fi
        ;;
    esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
