#!/usr/bin/env bash
TOTAL_WORKSPACES=10
NO_FOCUS_NO_WINDOW="assets/nfnw.svg"
NO_FOCUS_YES_WINDOW="assets/nfw.svg"
YES_FOCUS_NO_WINDOW="assets/fnw.svg"
YES_FOCUS_YES_WINDOW="assets/fw.svg"

declare -gA WORKSPACE_WINDOWS
declare -g FOCUSED_WORKSPACE_ID

update_focused_workspace() {
    case $line in
    workspacev2*)
        FOCUSED_WORKSPACE_ID="${line##*>>}"
        FOCUSED_WORKSPACE_ID="${FOCUSED_WORKSPACE_ID%%,*}"
        ;;
    esac
}

get_workspaces_with_windows() {
    WORKSPACE_WINDOWS=()
    while read -r id windows; do
        if [[ -n "$id" && "$id" != "null" ]]; then
            WORKSPACE_WINDOWS[$id]=$windows
        fi
    done < <(hyprctl -j workspaces | jq -r '.[] | "\(.id) \(.windows)"')
}

generate_widget() {
    local button_string=""
    local class="workspace-button"

    for i in $(seq 1 "$TOTAL_WORKSPACES"); do
        local image_path="$NO_FOCUS_NO_WINDOW"
        local has_windows=false

        if [[ -v WORKSPACE_WINDOWS[$i] && "${WORKSPACE_WINDOWS[$i]}" -gt 0 ]]; then
            has_windows=true
        fi

        if [[ "$i" == "$FOCUSED_WORKSPACE_ID" ]]; then
            if [[ "$has_windows" == true ]]; then
                image_path="$YES_FOCUS_YES_WINDOW"
            else
                image_path="$YES_FOCUS_NO_WINDOW"
            fi
        else
            if [[ "$has_windows" == true ]]; then
                image_path="$NO_FOCUS_YES_WINDOW"
            fi
        fi

        local image_string="(image :path \"$image_path\" :image-width 23 :image-height 23)"
        button_string+="(button :onclick \"hyprctl dispatch workspace $i\" :class \"$class\" $image_string)"
    done
    echo "(box :class \"workspaces-box\" :orientation \"h\" :spacing 0 :space-evenly false $button_string)"
}

update_widget() {
    generate_widget
}

FOCUSED_WORKSPACE_ID=$(hyprctl activeworkspace -j | jq '.id')
get_workspaces_with_windows
generate_widget

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock |
    while read -r line; do
        case "${line%%>>*}" in
        workspacev2)
            update_focused_workspace "$line"
            update_widget
            ;;
        openwindow | closewindow | movewindow)
            get_workspaces_with_windows
            update_widget
            ;;
        esac
    done
