[general]
working_directory = "C:/Users/makym"

[window]
dynamic_padding = true
decorations = "None"
opacity = 0.9
startup_mode = "Fullscreen"

[terminal]
shell = { program = "cmd.exe", args = ["/c", "wsl ~ && nu"] }

[mouse]
hide_when_typing = true

[font]
size = 12.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"
